### ISSUE TITLE
Hot reloading from routes other than main route breaks the page.

### ISSUE THREAD

**Issue by okumujustine** [CodeForUganda/techspaces-uganda#3]
# Description
When the page is reloaded from a different route than the main route, it's broken.

# Demo video
https://user-images.githubusercontent.com/22288040/124676488-4f95af00-dec7-11eb-8754-ac0b8bc2b018.mov

**Comment by okumujustine** [comment]
I will submit a PR on this today.

**Comment by luigimorel** [comment]
hey @okumujustine , thanks so much for this. apologies for the late response... been so busy
